olist/correios

- setup.py
The build wasn't including data files such as gifs and pngs. This caused the pdf generation to fail with many errors such as `FileNotFoundError ... /correios-pdf-generation-service/lib/python3.5/site-packages/correios/data/standard.gif'`.
This PR fix the package build to include these files.
> Fix setup: add gifs and pngs to package_data

- .travis.yml
- correios/utils.py
- tox.ini
Solves #27 
- Update travis.yml to test different versions
- Fix RangeSet to work on python 3.5.0 and 3.5.1
> Add support to python 3.5.* and 3.6.0 versions on tests

- correios/models/address.py
- correios/models/posting.py
- correios/renderers/pdf.py
- correios/utils.py
- tests/test_address_models.py
- tests/test_utils.py
- Capitalize address so there won't be many surprises on its length
- Delegate addresses' paragraph break to reportlab (words won't be cut or split by half)
- Remove overflowing space from shipping label boxes
The generated posting list PDF have its addresses cut short. Let's take the address "RUA Professor José Caetano dos Santos Mascarenhas" for example. It is currently being rendered as:
The generatedAfter the changes on this PR are applied:
> [V2-1803] Fix posting list pdf address

- correios/models/address.py
- correios/models/posting.py
- tests/test_address_models.py
Se o serumano digita o nome todo em maiúsculo o limite de caracteres dos nomes no PDF da PLP não funciona direito, vide o exemplo abaixo. Este PR corrige esse problema.
Antes do PR:
Depois:
> Capitalize names on the shipping label

- .bumpversion.cfg
- README.rst
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_client.py
- tests/test_pdf_renderer.py
- tests/test_xml_utils.py
We can declare requirements like:
* `correios>=1.0.0` - only model classes and validators
* `correios[pdf]>=1.0.0` - base installation + label/posting-list pdf generation
* `correios[client]>=1.0.0` - base installation + sigep/websro api client
* `correios[client,pdf]>=1.0.0` - full installation
> Make requirements granular and optional

- correios/exceptions.py
- correios/models/posting.py
- tests/conftest.py
- tests/test_posting_models.py
Improve package dimension validation to raise different exceptions for minimum vs. maximum invalid dimensions.
I'll wait for #34 merge and then bump minor version to make a release of this PR.
> Improve invalid package dimensions exceptions

- correios/client.py
- tests/fixtures/cassettes/test_calculate_delivery_time.yaml
- tests/fixtures/cassettes/test_calculate_delivery_time_except.yaml
- tests/test_client.py
In order to get delivery time estimation from Correios web services, I'm opening this pull request to add CalcPrazo operation[1].
I had to change the freight SoapClient instantiation adding `NoCache` because the tests were not passing[2]. According what I saw, suds lib uses schema cache and calling two different operations from suds Client (wsdl) makes it do not find proper data schema.
[1] - http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?op=CalcPrazo
[2] - https://travis-ci.org/olist/correios/jobs/257902922
> Add calc prazo method to correios client

- correios/client.py
- correios/soap.py
- requirements.txt
- tests/vcr.py
@osantana @georgeyk can someone help in rewriting vrc's files, and fix tests. 
When I delete vcr files, authentication fail.
> use Zeep instead of Suds

- correios/utils.py
- tests/test_utils.py
`3.1.0` broke because client try to load wsdl file from project who was installed.
> fix wsdl load after project update

- correios/client.py
- correios/models/data.py
- correios/models/posting.py
- correios/utils.py
- tests/fixtures/cassettes/test_calculate_freight_with_error_code_10_restricted.yaml
- tests/fixtures/cassettes/test_calculate_freight_with_error_code_11_restricted.yaml
- tests/fixtures/cassettes/test_calculate_freight_with_error_code_9_restricted.yaml
- tests/test_client.py
Adicionando os valores de frete no objeto `FreightError` pois quando o CEP é restrito os correios retornam com `erro=[9, 10, 11]` e nesse caso não é um erro de fato, mas o cliente tem a possibilidade de buscar o produto na agencia mais próxima.
> Set default freight values in case of error.

- correios/models/data.py
- requirements-test.txt
- tests/test_client.py
- tests/test_posting_models.py
The minimum declared value for all services has been updated by Correios. This PR update these values.
The minimum declared value per service is ten times the minimum basic value (currently 1.85[1]).
[1] - https://www.correios.com.br/para-voce/consultas-e-solicitacoes/precos-e-prazos/servicos-nacionais_pasta/carta
> Update services min declared value

- .gitignore
- correios/client.py
- correios/exceptions.py
- tests/fixtures/cassettes/test_client_authentication_error.yaml
- tests/test_client.py
Handle errors with lib's exceptions and do not propagate zeep Fault exception.
> Handle errors in _call method

- correios/client.py
- correios/exceptions.py
- tests/test_client.py
Create a ConnectTimeoutError in correios lib to handle ConnectTimeout errors from requests lib.
> Handle ConnectTimeout exceptions in _call method

- correios/client.py
- correios/exceptions.py
- tests/fixtures/cassettes/test_client_canceled_posting_card_error.yaml
- tests/fixtures/cassettes/test_client_nonexistent_posting_card_error.yaml
- tests/test_client.py
This PR aims to handle more specific errors, like posting list and posting card errors, to allow users to treat errors in a granular way. In addition don't need to import exceptions from another dependencies like `requests.exceptions.Timeout` or `zeep.exceptions.Fault`.
Unfortunately, errors are treated by checking error messages returned from `zeep.exceptions.Fault` because `code` attribute do not return any relevant information.
```python
(Pdb) exc.code
'soap:Server'
```
> Handle posting list and posting card errors

- correios/models/posting.py
- tests/test_posting_models.py
According to [new version of Correios' documentation](https://github.com/olist/correios/blob/master/documentation/v4-Manual_de_Implementacao_do_Web_Service_SIGEP_WEB.pdf), the package diameter only needs to be calculate if the object type is equal 003, cylinder, otherwise must return 0, as we can see in the image below.
> Fix Package diameter property

- correios/models/posting.py
- tests/test_posting_models.py
Starting 05/02 Correios will create a new package's extra cost. If the package is a cylinder or any dimension surpass 70 cm, will be an additional cost of R$ 20.00.
This PR add a method to verify if the package is mechanizable or not.
Correios explanation below:
[Carta 16.pdf](https://github.com/olist/correios/files/1960356/Carta.16.pdf)
> Add package is mechanizable validation

- correios/models/posting.py
- tests/test_posting_models.py
Some time ago correios changed how freight costs for "non mechanizable" packages [1] and we've already a property to determine whether a package is mechanizable (`Package.is_mechanizable`). This PR goes further and add a property to calculate its cost.
[1] https://www.correios.com.br/a-a-z/limites-de-dimensoes-e-peso
> Add non mechanizable cost to package

- tests/test_client.py
The last version for the zeep library [1] broke some tests for the correios library. This PR fixes these tests.
[1] https://github.com/mvantellingen/python-zeep/blob/master/CHANGES
> Fix tests for new zeep version

- tests/test_vcr.py
- tests/vcr.py
This PR makes easier the re-creation of cassettes and, more importantly, prevents contributors from committing their correios' username and password.
> Fix vcr to remove credentials before writing cassettes to file

- correios/models/data.py
- tests/test_posting_models.py
According to correios tracking docs [1] we were missing the tracking event BD[EIR] 80 for lost packages. This PR adds it. 
[1] page 19 on https://www.correios.com.br/a-a-z/pdf/rastreamento-de-objetos/manual_rastreamentoobjetosws.pdf
> Add lost tracking event

- correios/models/data.py
- documentation/modelo.xml
- tests/test_client.py
- tests/test_user_models.py
On August first Correios changed the "Valor Declarado" code from `019` to `064`. Starting August 10 they will stop accepting PLPs or tags using the old code.
> Change "Valor Declarado" code

- correios/models/data.py
- correios/models/posting.py
- correios/models/user.py
- tests/test_client.py
- tests/test_posting_models.py
- tests/vcr.py
- tox.ini
The minimum declared value for all services has been updated by Correios. This PR update these values (currently 19.5[1]).
[1] - https://www.correios.com.br/para-voce/consultas-e-solicitacoes/precos-e-prazos/servicos-nacionais_pasta/carta
> Update the minimum value of the declared value

- correios/models/data.py
- correios/models/posting.py
The tracking event FC-08 seems to be undocumented, but I guess the mapping in this PR are safe to production.
This is en example of events where we could find this event (fc-08):
```
('delivered', 'Objeto entregue ao destinatário', 'Recebido por:', 'Finalizar a entrega. Não é mais necessário prosseguir com o acompanhamento.')
('shipped', 'Objeto saiu para entrega ao destinatário', '', 'Acompanhar')  
('shipped', 'Área com distribuição sujeita a prazo diferenciado', 'Restrição de entrega domiciliar temporária', 'Acompanhar')
('shipped', 'Objeto encaminhado para', '<nome da cidade>', 'Acompanhar')
('shipped', 'Objeto postado', '', 'Acompanhar')
```
Also, I could not find any tests for specific tracking events, so I left it as is.
> Handle fc 8

- correios/models/address.py
- correios/models/posting.py
- tests/test_posting_models.py
Corrige a geração da função de datamatrix que gera o código de barras.
O campo complement é muito permissivo, então faço com que na geração da datamatrix do código de barras ele considere apenas os algarismos alfanuméricos do complemento e ainda preenche o resto a esquerda com zeros, como fazem outros pedaços da damatrix.
> Fix datamatrix generation cause for bad formating address complement

- correios/models/data.py
- tests/test_posting_models.py
We started to receive CMR as an event type and because of the error raised by the lib a few packages are not being correctly tracked.
> Add new event type

- correios/models/data.py
Payload sample (redacted):
```
{
'tipo': 'BDR',
'status': '15',
'data': '07/03/2019',
'hora': '12:16',
'descricao': 'Recebido na unidade de distribuição',
'detalhe': 'Por determinação judicial o objeto será entregue em até 7 dias',
'recebedor': None,
```
It is quite similar to https://github.com/olist/correios/pull/142
> Add mapping for BDR event, status=15

- correios/models/data.py
We are receiving a few tracking events with this status. 
Sample payload:
```
{
'tipo': 'BDI',
'status': '39',
'descricao': 'A entrega não pode ser efetuada',
'detalhe': 'Objeto em análise de destinação',
```
> Add tracking status

- correios/models/data.py
A couple unexpected status we started to receive from Correios.
Sample payloads:
```
'tipo': 'CAR',
'status': '01',
'descricao': 'Conferido',
'detalhe': 'Recebido na unidade de destino',
```
```
'tipo': 'BDR',
'status': '39',
'descricao': 'A entrega não pode ser efetuada',
'detalhe': 'Objeto em análise de destinação',
```
> Add new status

- correios/models/data.py
We are receiving a few tracking events with this status.
Sample payload:
```
'tipo': 'FC',
'status': '10',
'descricao': 'Objeto recebido na unidade de distribuição',
'detalhe': 'Entrega prevista para o próximo dia útil',
```
> Add new tracking status

- correios/models/data.py
We started to receive a few new tracking statuses from Correios.
They are not present in the documentation, so I tried to make an "educated guess" about them by looking at the response content and consulting a few in the Correios website.
All objects were shipped and those statuses seems to be non-terminative.
Redacted samples:
```
'tipo': 'BDI',
'status': '14',
'descricao': 'Desistência de postagem pelo remetente',
'detalhe': None,
```
```
'tipo': 'BLQ',
'status': '02',
'descricao': 'Tentativa de suspensão da entrega',
'detalhe': 'Objeto em análise de destinação',
```
```
'tipo': 'BDR',
'status': '60',
'descricao': 'O objeto encontra-se aguardando prazo para refugo',
'detalhe': None,
```
```
'tipo': 'BDI',
'status': '60',
'descricao': 'O objeto encontra-se aguardando prazo para refugo', …
```
> Add new tracking statuses

- .travis.yml
- tox.ini
Update and reduce the number of patch versions used in the build process.
Add Python 3.7.
> Update python versions used in travis

- correios/models/builders.py
- tests/test_builders.py
Although a Package from the `BOX` type should not have any values for `diameter` we are receiving this when fetching PostInfos.
This causes an exception to be raised when validating the Package measures, and the user could not recover properly and treat this.
In order to make this method more functional, I'm filtering the measures fields that makes sense to each Package type prior to the instance creation.
> Remove incorrectly returned fields by Correios WS for each package type

- correios/models/builders.py
- correios/models/posting.py
- tests/test_builders.py
Adiciona validação no builder do Receipt, para não criar o Receipt caso a posting list ainda não tenha sido processada. Pois os campos que são necessários para sua criação, só são inseridos quando a posting list é processada, o que acaba gerando o erro `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'` [nesse ponto](https://github.com/olist/correios/blob/master/correios/models/posting.py#L496). Também geraria exception nos outros campos, só acaba estourando nesse primeiro cast.
Exemplo de como vem os campos quando a posting list ainda não foi processada:
```
<objeto_postal>
<status_processamento>0</status_processamento>
<data_postagem_sara />
<numero_comprovante_postagem />
<valor_cobrado />
</objeto_postal>
```
> Add validation on the Receipt builder

- correios/models/address.py
- requirements-test.txt
- tests/test_posting_models.py
Previous code didn't work for all cases of non-ascii characters in complement field.
This change also tries to replace accented characters with their ascii versions, and keeps the whitespaces since I couldn't find a reason to remove them.
*Pinned pytest version until pytest-factoryboy supports it's new version.
> Fix complement_safe_display ascii conversion

- correios/renderers/pdf.py
To be consistent in which weight values are used in the PDF Renderer.
The weight property is already used in the Shipping Label.
> Use same package weight in posting list table as in shipping label

- .isort.cfg
- .pre-commit-config.yaml
- .travis.yml
- pyproject.toml
Update Python version matrix used by Travis CI, update pre-commit hooks and add isort to them.
> [TINB-345] Update Python version matrix and pre-commit hooks

- correios/client.py
- pyproject.toml
- tests/test_client.py
We are receiving some strange posting list cases:
SIGEP Web accuses an error, but the posting list gets approved on SARA
Posting List is closed by SIGEP web but has rejected objects on SARA.
This PR sends the original error returned by SIGEP web to help us to evaluate those cases.
I did it by setting the exception's `__cause__`, since I think it has the least impact on the API.
> Send the original Fault as the cause of the ClosePostingListException

- correios/models/data.py
- tests/test_client.py
- tests/test_posting_models.py
Correios readjusted the minimum declared value from 19.50 to 20.50.
This PR updates this value to every PAC and SEDEX service in this lib
> Update minimum declared value for PAC and SEDEX to 20.50 BRL

- correios/models/data.py
- correios/models/user.py
- correios/serializers.py
- tests/test_client.py
- tests/test_user_models.py
**What**
Remove a tag `<valor_declarado></valor_declarado>` do xml enviado na contratação dos correios
**Why**
Hoje, todos os contratos possuem seguro, que na maiorias das vezes não é utilizado e gastamos dinheiro a toa.  Para remover a contratação, devemos zerar o valor da tag `<valor_declarado>` e eliminar as tags de serviço adicional com códigos 19, 64 ou 65.
`Story`: https://jira-olist.atlassian.net/browse/LOG1-755
`Task`: https://jira-olist.atlassian.net/browse/LOG1-782
> [LOG1-782] -  Remove declared_value from xml

- correios/serializers.py
- tests/test_client.py
- tests/test_user_models.py
Fix max_length on XML
The Renderization of XML is fetching the total size of the string. This PR prevent this long string based on max_lenght rule of field
> Fix max_length on XML

- correios/models/data.py
Adiciona um status faltante (BDI/79) aos dados mantidos.
> [LOG1-1338] Add missing BDI/79 tracking status
